### ISSUE TITLE
Foutmelding contactformulier verborgen voor screenreaders

### ISSUE THREAD

**Issue by sophieschoice** [frankanysurfer/Diax#14]
![CleanShot 2021-04-27 at 14 11 29@2x](https://user-images.githubusercontent.com/2573361/116239092-8a11fb80-a762-11eb-8ce4-ba6d8e1ffac6.png)

De algemene foutmelding van het formulier wordt verborgen voor screenreaders door het gebruik van aria-hidden. Verwijder dit attribuut en maak gebruik van role-alert om screenreaders te verwittigen van de foutboodschap: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Alert_Role 

<img width="725" alt="CleanShot 2021-04-27 at 14 16 27@2x" src="https://user-images.githubusercontent.com/2573361/116239628-2c31e380-a763-11eb-9e7b-6a6e0aa237c1.png">

De foutboodschappen bij de velden zelf worden ook verborgen met aria-hidden. Verwijder het attribuut daar.

**Comment by frankanysurfer** [comment]
De algemene foutmeldingen staan in inderdaad verborgen voor screenreaders. Maar vlak daarboven in de code staan de screenreader foutmeldingen, die zijn dan weer visueel verborgen. Die foutmeldingen zijn meer aangepast voor screenreadergebruikers.
