### ISSUE TITLE
Cookie-melding in een modal dialog

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#22]
<img width="958" alt="CleanShot 2021-05-05 at 15 27 31@2x" src="https://user-images.githubusercontent.com/870049/117148413-7c89f080-adb6-11eb-956a-5fc1ce676402.png">

De huidige cookie-banner kan niet gesloten worden met het toetsenbord. Het lukt me niet om die de focus te geven. Het is een button dus hij zou wel in de tabvolgorde moeten zitten. Het is overlay die het menu verbergt en dus problematisch.

Ik zou sowieso niet voor een overlay kiezen. Beter een modal dialog dat alles blokkeert. Andere plugin zoeken?

**Comment by frankanysurfer** [comment]
Bij de meeste cookie plugins moet je door de hele pagina tabben om focus te krijgen. Degene die ik nu gebruik heeft onmiddellijk focus. Werkt prima op chrome; firefox en edge. Misschien werk je met safari want dat heb ik niet kunnen testen. Een plugin met een modal dialog heb ik nog niet gevonden.

**Comment by Veyfeyken** [comment]
De huidige cookie-plugin is niet toegankelijk.
![Uploading CleanShot 2021-05-07 at 11.02.11@2x.png…]()

Ken je een andere plugin om een toegankelijke modal dialog te implementeren? Dat lijkt me een prima alternatief.

**Comment by Veyfeyken** [comment]
We kunnen niet lanceren met een ontoegankelijke cookie-plugin. Niet sluiten aub.

**Comment by frankanysurfer** [comment]
Hier zit ik wel vast, iemand die verstand heeft van cookie banners?

**Comment by frankanysurfer** [comment]
Bij zowat alle cookie-plugins moet je eerst door de hele pagina tabben voor je aan de cookie banner komt.
Nu heb ik er toch een gevonden (Responsive Cookie Consent ) die je met het toetsenbord kan bedienen. Werkt alvast met chrome, firefox en edge.

**Comment by Veyfeyken** [comment]
Deze is wel ok denk ik.
Kan je de link "more info" wissen en de link "accept" vertalen naar "accepteren"? 

En de tekst aanpassen:
"We gebruiken enkel cookies voor analytische doeleinden."

Voor EN:
"We use cookies for analytical purposes only."

Voor FR best even aan Sophie of Pierre vragen.

**Comment by Veyfeyken** [comment]
De live cookiebanner staat momenteel in het Nederlands op alledrie de taalversies.

<img width="1256" alt="CleanShot 2021-06-09 at 08 23 09@2x" src="https://user-images.githubusercontent.com/870049/121303930-f48a8f80-c8fb-11eb-8672-c07404487d08.png">

**Comment by Veyfeyken** [comment]
De link "meer info" leidt naar een pagina die niet bestaat. Wis de link.
![CleanShot 2021-06-09 at 08 32 51@2x](https://user-images.githubusercontent.com/870049/121305016-5dbed280-c8fd-11eb-82f8-27665cff7eaa.png)

**Comment by Veyfeyken** [comment]
De link "accepteren" scoort onvoldoende op contrast, gebruik de kleurcombinaties van de huisstijl.

<img width="576" alt="CleanShot 2021-06-09 at 09 38 30@2x" src="https://user-images.githubusercontent.com/870049/121313485-ba72bb00-c906-11eb-8553-c782eb6c60e0.png">

**Comment by frankanysurfer** [comment]
De vertaling en de kleuren zijn aangepast.
