### ISSUE TITLE
Vette tekst is amper te onderscheiden

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#27]
In deze tekst (op de [pagina wetgeving](https://staging.di-ax.be/wetgeving/)) zijn bijvoorbeeld de woorden **overheden** en **toegankelijkheidsverklaring** vetgedrukt, maar dat zie je amper. 

<img width="754" alt="2021-05-07_PrtScr_11Ways_zd3I1XK9@2x" src="https://user-images.githubusercontent.com/103744/117428040-f55b8a80-af25-11eb-9ec4-28dc00e866d7.png">

Kan je nakijken of je de juiste weights van de fonts inlaadt? Vette tekst moet beter ondescheidbaar zijn van de reguliere tekst.

**Comment by frankanysurfer** [comment]
Werk je met safari? Het ziet er bij in mij chrome veel beter uit.
![image](https://user-images.githubusercontent.com/67426700/117430995-fb9f3600-af28-11eb-92c0-6891988df04f.png)

Ik heb nu de paragraaf de laagste dikte en de strong de hoogste gegeven. Als het nog niet OK is kan ik misschien de strong een donkerblauwe kleur geven?

```
p {
    font-weight: 100;
}

b, strong {
   font-weight: 900;
}
```

**Comment by roelvangils** [comment]
Zeker niet donkerblauw maken. Het is nog niet opgelost in Safari.

**Comment by Veyfeyken** [comment]
In macOS Chrome is het ook niet sterk genoeg.

<img width="730" alt="CleanShot 2021-05-13 at 11 36 41@2x" src="https://user-images.githubusercontent.com/870049/118107825-88da0300-b3df-11eb-9238-fcb6512a592e.png">

**Comment by frankanysurfer** [comment]
Is dit nu in orde?

**Comment by Veyfeyken** [comment]
Neen. Onveranderd.

**Comment by Veyfeyken** [comment]
Dit is niet opgelost. Niet sluiten aub.

**Comment by frankanysurfer** [comment]
Ok, kijk ik morgen naar.

**Comment by roelvangils** [comment]
<img width="801" alt="20210607_PrtScr_11Ways_TsF1j9NZ@2x" src="https://user-images.githubusercontent.com/103744/121060029-665ebe00-c7c2-11eb-9f3b-31eb193c6286.png">

@frankanysurfer, @Veyfeyken zo goed?

Frank, ik zag dat je font-weight: 900 gebriukt had voor het font "open_sans" maar dat font had geen bold variant. Ik zag dat je allemaal aparte web fonts inlaadt, zoals deze:

```
@font-face {
    font-family: 'open_sansbold';
    src: url('font/opensans-bold-webfont.woff2') format('woff2'),
         url('font/opensans-bold-webfont.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
```

Maar die gebruikt je nog niet. Nu is her dus wel vet, maar ik denk dat je best wel eens kijkt om wat te snoeien in alle web fonts die je inlaadt, want de helft gebruik je niet.

Je moet deze change zelf wel nog committen.

**Comment by roelvangils** [comment]
Zie _font.scss trouwens

**Comment by frankanysurfer** [comment]
'k Heb een aanpassing gedaan, werkt dit?

`b, strong {
    font-family: 'open_sansbold';
}`

**Comment by Veyfeyken** [comment]
Yep. Dat werkt.

**Comment by Veyfeyken** [comment]
<img width="976" alt="CleanShot 2021-06-08 at 09 19 19@2x" src="https://user-images.githubusercontent.com/870049/121141078-db6dda00-c83a-11eb-842d-222908c26db2.png">

**Comment by Veyfeyken** [comment]
Dat werkt.
