### ISSUE TITLE
Een cookie consent is verplicht

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#38]
Een site die Google Analytics gebruikt heeft verplicht een cookie notice nodig (we gebruiken tracking cookies). Zonder die cookie notice zijn we niet in orde met de EU-regelgeving en dat zou nogal ironisch zijn aangezien we zelf zwaaien met EU-wetgeving op onze site. De site kan dus niet online zonder cookie consent.

De [cookie consent kit van de EC](https://wikis.ec.europa.eu/display/WEBGUIDE/04.+Cookies) kan helpen.

**Comment by frankanysurfer** [comment]
Ik heb de Cookie consent kit code:

`<script type="application/json">{
  "utility": "cck",
  "url": {
    "en": "https://di-ax.be/en",
    "nl": "https://di-ax.be",
    "fr": "https://di-ax.be/fr"
  }
}</script>`

Ik weet eigenlijk niet hoe het werkt, er valt niets te downloaden of zo, maar dit stukje code zou voldoende zijn.
