### ISSUE TITLE
Stoefbalk met logo's klanten op homepage

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#41]
@roelvangils

**Comment by roelvangils** [comment]
@frankanysurfer deze is nog belangirjk: een balk met logo's van organiaties waar we mee samenwerken.

<img width="865" alt="Mockup stoefbalk" src="https://user-images.githubusercontent.com/103744/117999110-d190ae00-b344-11eb-9e26-a75cc5c96847.png">

Zie [Figma](https://www.figma.com/file/fvFhkWTW0RRbLWw7E62jfN/Stoefbalk-DiAX?node-id=0%3A1) (in hogere resolutie) 

Daar kan je de logo's exporteren naar PNG. Enkele tips:

- Exporteer de logo's als PNG @2 (dubbele resolutie voor Retina-schermen) met witte achtergrond. De border rond de images geef je best later met CSS.
- Vergeet niet elk logo een alt-attribuut te geven (de naam van de organisatie); je hoeft niet te linken naar hun websites.
- Plaats de "stoefbalk" voorlopig onder de quote. Misschien gaan we nog vragen om hem te verplaatsen, dus hou daar ook rekening mee. 
- CSS: zorg voor nette padding en hou de responsiveness in de gaten (de logo's hoeven niet kleiner te worden, wel wrappen).
- Gebruik best onderstaande HTML-structuur als basis voor de "stoefbalk"

```html
<h2>Deze organisaties vertrouwen op de expertise van DiAX</h2>
<ul>
    <li><img src="logo-betawerk.png" alt="Digipolis"></li>
    <li><img src="logo-abb.png" alt="Agentschap Binnenlands Bestuurd (Vlaamse overheid)"></li>
  (Etc.)
</ul>
```

**Comment by frankanysurfer** [comment]
Stoefbalk staat op de site.

**Comment by roelvangils** [comment]
Nice! Als je nu je nieuwe project gebruikt, kan je het issue verschuiven naar een kolom Review zodat wij kunnen checken!

**Comment by roelvangils** [comment]
Indien mogelijk, mogen de logo's van mij wel een stukje kleiner (75% of zo). Ze zijn nu nogal massive 🙂

En check je responsiveness nog even, want soms lopen ze wat raar:

![Uploading 2021-05-17_PrtScr_11Ways_fyVDvn9H@2x.png…]()

**Comment by frankanysurfer** [comment]
De logo's zijn nu kleiner. Opvraag van Erik staan ze nu ook op over Diax.
