### ISSUE TITLE
Project Board maken

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#43]
Hey @frankanysurfer!

Hoe is het ermee? 

Jij kan als beheerder een [project board](https://github.com/frankanysurfer/Diax/projects) maken voor deze repository. Zo kunnen we alle overblijvende issues voor de site gaan prioriteren. Wil je van mij, Gijs, Bart en Erik ook contributors maken van jouw reposiory? Zo kunnen we wat beter samenwerken en heb ik ook controle over het project.

We hebben nog 3 (werk)dagen tot 20 mei en dan gaat de site live!

Roel

**Comment by frankanysurfer** [comment]
Is gebeurd.
