### ISSUE TITLE
Foutjes in de CSS Switcher

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#44]
- De labels zijn nu in CAPS ("DONKERE MODUS" en "LICHTE MODUS"). Maak daar "Donkere modus" en "Lichte modus" van.
- De labels zijn nu omgekeerd. Als de lichte modus actief is, moet het label van de knop "Donkere modus" zijn en omgekeerd. 
- Indien mogelijk: respecteer de systeeminstelling (zie [Dark Mode in CSS](https://css-tricks.com/dark-modes-with-css/)). Als dat even wat te veel werk is, heeft dat nu niet de hoogste prio hoor.

**Comment by frankanysurfer** [comment]
Ik heb de knoppen omgewisseld.

**Comment by frankanysurfer** [comment]
Er is ook een prefers-color-scheme: dark
