### ISSUE TITLE
Layout footer verbeteren

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#45]
Huidig:
<img width="1509" alt="CleanShot 2021-05-13 at 11 24 41@2x" src="https://user-images.githubusercontent.com/870049/118107390-fafe1800-b3de-11eb-9ebb-7bd6a6b11fef.png">

Suggestie (snel gephotoshopped):
![Artboard 1](https://user-images.githubusercontent.com/870049/118107552-2d0f7a00-b3df-11eb-8f4a-76db9f5c2c6a.png)

Verander de kop "DiAX" erboven best in "Sitemap".

**Comment by Veyfeyken** [comment]
Er kan nog een link "algemene voorwaarden" bijkomen.

**Comment by frankanysurfer** [comment]
Is aangepast.
