### ISSUE TITLE
Probleem met responsiveness en Dark Mode op iOS

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#46]
https://user-images.githubusercontent.com/103744/118410413-95848280-b68f-11eb-9d8f-967bd4d4e732.MOV

Wanneer je OS al in donkere modus staat, en je switcht dan naar het donkere thema op de website, dan gebeurt er iets raars.

Ook zou je de responsive breakpoints nog eens goed moeten bekijken. In het ontwerp van Seppe zijn de navigatie-items ook niet zo groot, geloof ik, en zijn ze rechts uitgelijnd.

**Comment by frankanysurfer** [comment]
Dit is vervelend, kan de fout niet simuleren. Wil je dat ik de font grootte van links kleiner zet? Voor rechts uit te lijnen zijn er teveel items.

**Comment by frankanysurfer** [comment]
Dit is opgelost.
