### ISSUE TITLE
legend van fieldset wissen voor contactformulier

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#47]
Een fieldset met legend is overbodig en dubbele informatie. De border die de fieldset rond het formulier zet is op zich niet verkeerd. Het is vooral de legend erboven. Die voegt niets nuttigs toe. Dat is enkel nuttig voor uitgebreide formulieren waar je verschillende groepen van velden wil samenzetten. 

<img width="829" alt="CleanShot 2021-05-17 at 14 51 11@2x" src="https://user-images.githubusercontent.com/870049/118491479-556ce080-b71f-11eb-824c-6b59c8051705.png">

**Comment by frankanysurfer** [comment]
legend gewist
