### ISSUE TITLE
Issues met donkere modus op Windows

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#48]
Als je Windows gebruikt met een donker thema, dan werkt onze Dark Mode niet goed. 

![slack-imgs](https://user-images.githubusercontent.com/103744/118513122-b0103780-b733-11eb-9bdf-1b32998df3c2.png)

Voor mij is dit nu wel geen prio. Ik denk dat je beter eerste de footer in orde brengt en desnoods de "Dark mode" button verbergt tot wanneer hij volledig goed werkt.

**Comment by frankanysurfer** [comment]
Dit is aangepast, ik kijk het mobiele menu nog na.
