### ISSUE TITLE
formuliervalidatie

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#49]
> Een of meer velden bevatten een fout. Graag verbeteren en opnieuw proberen.

Kunnen de foutieve velden hier vermeld worden, anders is deze boodschap niet echt zinvol.

De foutmeldingen bij de velden hebben een aria-hidden="true" attribuut. Ze zijn ook niet correct verbonden aan de input via aria-describedby.

<img width="599" alt="CleanShot 2021-05-18 at 09 25 35@2x" src="https://user-images.githubusercontent.com/870049/118609440-070d1f80-b7bb-11eb-968e-e454851b37aa.png">

**Comment by frankanysurfer** [comment]
Ik gebruik Contact form 7 plugin en heb die geconfigureerd volgens [deze methode](https://rianrietveld.com/2014/03/how-to-set-up-an-accessible-form-using-contact-form-7-in-wordpress/)
De foutmeldingen voor ziende en sreenreaders zijn afzonderlijk. Boven de zichtbare foutmeldingen staan die voor screenreadergebruikers.

**Comment by Veyfeyken** [comment]
@bart, wil jij de formuliervalidatie van het contactformulier eens even testen?

**Comment by Veyfeyken** [comment]
Ik vind het ok. Maar nog steeds:
    Er is een fout opgetreden bij het
        versturen van het bericht. Probeer later nog een keer.
    
      
    Wordpress kan ook geen mails sturen om
        je wachtwoord te resetten enz.
    
      
    
      
    Bart Simons 
Web accessibility specialist
AnySurfer
Tel: 02-210 61 49
    Op 18/05/2021 om 13:59 schreef Gijs
      Veyfeyken:
    
    
      
      @bart, wil jij de formuliervalidatie van het contactformulier eens
      even testen?
      
        
          On 18 May 2021, at 11:50, frankanysurfer ***@***.***>
            wrote:
          
          
            
            
            Ik gebruik Contact form 7 plugin en heb die
              geconfigureerd volgens deze
                methode
              De foutmeldingen voor ziende en sreenreaders zijn
              afzonderlijk. Boven de zichtbare foutmeldingen staan die
              voor screenreadergebruikers.
            —
              You are receiving this because you authored the thread.
              Reply to this email directly, view it on GitHub,
              or unsubscribe.

**Comment by frankanysurfer** [comment]
De foutmelding zou aan de server liggen, Jelle ging er naar kijken.

**Comment by roelvangils** [comment]
Plug-in is fout geconfigureerd. Mailsever zou moeten werken.
