### ISSUE TITLE
Links zijn niet herkenbaar

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#50]
Ik had niet door dat dit links waren op de homepage tot ik er met het toetsenbord op kwam.

<img width="661" alt="CleanShot 2021-05-18 at 11 31 13@2x" src="https://user-images.githubusercontent.com/870049/118628179-ac7cbf00-b7cc-11eb-999b-dd6dacd3617f.png">

**Comment by frankanysurfer** [comment]
De links zijn nu ook in lijsten onderlijnd.
