### ISSUE TITLE
Social media links in footer

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#51]
<img width="346" alt="2021-05-19_PrtScr_11Ways_wX6F4X1I@2x" src="https://user-images.githubusercontent.com/103744/118806343-3ac57380-b8a7-11eb-9f1a-173bbd6d2215.png">

- Linkedin: https://www.linkedin.com/company/di-ax/
- Twitter: https://twitter.com/DiAX_be

Gebruik liefst de iconen die Seppe voorzien heeft.

**Comment by frankanysurfer** [comment]
Twitter en Linkedin toegevoegd
