### ISSUE TITLE
Wit blok in footer moet vaste breedte krijgen

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#56]
Nu wordt het blok breder of smaller wanneer de titel breder of smaller is. Bij "contact us" loopt het mis.

<img width="468" alt="2021-05-26_PrtScr_11Ways_tD5891u9@2x" src="https://user-images.githubusercontent.com/103744/119707719-c2892000-be5b-11eb-8191-fc3eea8cf57b.png">

Het gaat om blokje `.site-info`.

**Comment by frankanysurfer** [comment]
Ik heb het blok een minimum breedte gegeven.
