### ISSUE TITLE
Google Analytics toevoegen

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#59]
Erik heeft een GA-code aangemaakt voor het domein `di-ax.be`. Frank, kan jij de analytics code toevoegen in het basistemplate van de website?

De code is `198965149`.

Meer info: [How to Add Google Analytics to WordPress Without a Plugin](https://www.monsterinsights.com/how-to-add-google-analytics-to-wordpress-without-a-plugin/)

**Comment by roelvangils** [comment]
@frankanysurfer je had mij gemaild hierover zag ik, maar het is echt handiger om hier te antwoorden. Ik probeer mijn mailbox onder controle te houden 🙂

**Comment by frankanysurfer** [comment]
Ik heb de link gevolgd om Google Analytics zonder plugin te installeren, dit is de code die ik in de header heb geplaatst:

`<script async src="https://www.googletagmanager.com/gtag/js?id=G-198965149"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-198965149');
</script>`

**Comment by roelvangils** [comment]
Werkt dit nu? Wie heeft er zicht op de analytics? Ben benieuwd.

**Comment by frankanysurfer** [comment]
Heeft Erik daar geen zicht op? Hij heeft toch de GA-code aangemaak?

**Comment by Veyfeyken** [comment]
Ik denk niet dat we aan het registreren zijn. Ik krijg helemaal niets te zien als ik met info@di-ax.be inlog. 

@frankanysurfer Zou je Matomo plugin voor Wordpress willen installeren?
https://matomo.org/installing-matomo-for-wordpress/

Dat is eenvoudiger en duidelijker dan Google Analytics.

**Comment by Veyfeyken** [comment]
Als dat gebeurd is mag je de analytics code verwijderen.

**Comment by Veyfeyken** [comment]
Matomo is geïnstalleerd. Zie backend. Dit issue mag gesloten worden.
