### ISSUE TITLE
Font laadt niet in (live site)

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#60]
<img width="1392" alt="CleanShot 2021-06-09 at 08 24 09@2x" src="https://user-images.githubusercontent.com/870049/121304056-24d22e00-c8fc-11eb-865f-3c2a8e8e4319.png">

**Comment by roelvangils** [comment]
Oei! Dat had ik zelf nog niet gezien. In Safari werkt het wel (ook na cache legen). @frankanysurfer, enig idee? Anders vraag ik het eens aan Jelle.

**Comment by roelvangils** [comment]
Update: nu werkt het ineens wel (in Chrome). Na refreshen. Weet niet waar het aan lag. Werkt het bij jullie nu ook?

**Comment by Veyfeyken** [comment]
Font laadt nog steeds niet in. Ook niet na refresh. Chrome.

**Comment by frankanysurfer** [comment]
Daarnet waren de font goed, nu niet meer, vreemd.

**Comment by Veyfeyken** [comment]
@roelvangils

**Comment by Veyfeyken** [comment]
<img width="1557" alt="CleanShot 2021-06-11 at 14 12 44@2x" src="https://user-images.githubusercontent.com/870049/121684557-20a23e00-cabf-11eb-82e8-2af48c3362b1.png">

**Comment by Veyfeyken** [comment]
@roelvangils 
Dit is wel zwaar problematisch en staat nu zo al behoorlijk lang live. Ik kan er zelf helaas niet mee helpen.

**Comment by frankanysurfer** [comment]
Ik dacht dat dit al opgelost was, bij mij gaat het goed. Op deze pagina staat een mogelijke oplossing:
[https://crunchify.com/how-to-fix-access-control-allow-origin-issue-for-your-https-enabled-wordpress-site-and-maxcdn/](url)
Dit stukje code:
`<IfModule mod_headers.c>
  <FilesMatch "\.(ttf|ttc|otf|eot|woff|woff2|font.css|css|js)$">
    Header set Access-Control-Allow-Origin "*"
  </FilesMatch>
</IfModule>`
moet je toevoegen in .htacccess 
Maar ik kan het niet doen, ik heb geen schrijfrechten op dat bestand.
