### ISSUE TITLE
Logo wordt niet geladen in donkere modus 

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#61]
Lichte modus (werkt):

```html
<img id="diax-logo" src="https://www.di-ax.be/wp-content/uploads/2021/03/diax-logo.svg" alt="Diax Digital Accessibility Experts">
```

Donkere modus (werkt niet meer door verhuis)

```html
<img id="diax-logo" src="https://staging.di-ax.be/wp-content/themes/diax/img/diax-logo-dark.svg" alt="Diax Digital Accessibility Experts">
```

Dat is ergens hard-coded in gezet (in de plugin setting)? Dat is iets wat jij best bekijkt, @frankanysurfer. Verander je meteen ook de alt-tekst naar `DiAX (Digital Accessibility Experts`? Best nergens Diax gebruiken; de goede schrijfwijze is DiAX! 😉 Puntjs op de i!

**Comment by frankanysurfer** [comment]
Is aangepast
