### ISSUE TITLE
Faux italics vervangen door echte italic variant van het font

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#67]
Beter de echte italic variant inladen van het font. Dit ziet er niet professioneel uit (faux italics is ook slechter leesbaar).

<img width="1049" alt="20210619_PrtScr_11Ways_D7GU9ekT@2x" src="https://user-images.githubusercontent.com/103744/122650898-a7958d00-d135-11eb-8311-c124fb307d9a.png">

**Comment by frankanysurfer** [comment]
Is aangepast
