### ISSUE TITLE
taalkeuze menu overlapt met logo op mobiel

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#68]
![IMG_6104](https://user-images.githubusercontent.com/870049/123219303-09a31900-d4cd-11eb-87dc-4323fff9b735.PNG)

**Comment by roelvangils** [comment]
Deze staat al lang open. Wordt hier nog wat mee gedaan of gaan we dat zo laten?

**Comment by frankanysurfer** [comment]
Dit is voor mij in orde.

**Comment by Veyfeyken** [comment]
Ik kan het niet langer reproduceren.
