### ISSUE TITLE
Issue met fonts van links

### ISSUE THREAD

**Issue by roelvangils** [frankanysurfer/Diax#7]
Inline links worden in een kleiner font weergegeven dan de omliggende tekst. Dat lijkt op een bug.

<img width="1017" alt="screenshot-Gl3A6S1D@2x" src="https://user-images.githubusercontent.com/103744/116233621-cf7efa80-a75b-11eb-92d4-5555e47ea0d7.png">

**Comment by sophieschoice** [comment]
Op de pagina "Partners" worden links naar de websites groter weergegeven dan de tekst:

<img width="641" alt="CleanShot 2021-04-27 at 14 01 45@2x" src="https://user-images.githubusercontent.com/2573361/116238073-3a7f0000-a761-11eb-8c6e-5d909447103d.png">

Lijkt me ook een bug.
