### ISSUE TITLE
logo Stad Antwerpen toevoegen op de homepage

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#75]
Onder de kop "Deze organisaties vertrouwen op de expertise van DiAX"

**Comment by Veyfeyken** [comment]
svg vind je hier:
https://cdn.antwerpen.be/core_branding_scss/4.2.2/assets/images/a-logo.svg

**Comment by frankanysurfer** [comment]
Logo Antwerpen staat erop.
