### ISSUE TITLE
Contactformulier werkt niet

### ISSUE THREAD

**Issue by Veyfeyken** [frankanysurfer/Diax#76]
![screenshot2021-09-17at09 31 18@2x](https://user-images.githubusercontent.com/870049/133743068-710d8d29-8e6b-4ce3-80bb-ea0780e18a1d.jpg)

**Comment by Veyfeyken** [comment]
"probeer later nog een keer" is geen goede foutmelding. Beter veranderen in "stuur ons een e-mail naar info@di-ax.be"?

**Comment by frankanysurfer** [comment]
De foutmelding is aangepast.

**Comment by Veyfeyken** [comment]
Je kan het probleem niet vinden/oplossen? Dan beter geen formulier publiceren.

**Comment by Veyfeyken** [comment]
Best offline halen in tussentijd.

**Comment by frankanysurfer** [comment]
Contactformulier is voorlopig offline.

**Comment by roelvangils** [comment]
Ik ga deze sluiten.
